// Code generated by protoc-gen-go. DO NOT EDIT.
// source: environmentalist.proto

package environmentalistpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HashicorpVault_NewSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	SecretValut          string   `protobuf:"bytes,2,opt,name=secretValut,proto3" json:"secretValut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashicorpVault_NewSecretRequest) Reset()         { *m = HashicorpVault_NewSecretRequest{} }
func (m *HashicorpVault_NewSecretRequest) String() string { return proto.CompactTextString(m) }
func (*HashicorpVault_NewSecretRequest) ProtoMessage()    {}
func (*HashicorpVault_NewSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{0}
}

func (m *HashicorpVault_NewSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashicorpVault_NewSecretRequest.Unmarshal(m, b)
}
func (m *HashicorpVault_NewSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashicorpVault_NewSecretRequest.Marshal(b, m, deterministic)
}
func (m *HashicorpVault_NewSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashicorpVault_NewSecretRequest.Merge(m, src)
}
func (m *HashicorpVault_NewSecretRequest) XXX_Size() int {
	return xxx_messageInfo_HashicorpVault_NewSecretRequest.Size(m)
}
func (m *HashicorpVault_NewSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashicorpVault_NewSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashicorpVault_NewSecretRequest proto.InternalMessageInfo

func (m *HashicorpVault_NewSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *HashicorpVault_NewSecretRequest) GetSecretValut() string {
	if m != nil {
		return m.SecretValut
	}
	return ""
}

type HashicorpVault_NewSecretResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashicorpVault_NewSecretResponse) Reset()         { *m = HashicorpVault_NewSecretResponse{} }
func (m *HashicorpVault_NewSecretResponse) String() string { return proto.CompactTextString(m) }
func (*HashicorpVault_NewSecretResponse) ProtoMessage()    {}
func (*HashicorpVault_NewSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{1}
}

func (m *HashicorpVault_NewSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashicorpVault_NewSecretResponse.Unmarshal(m, b)
}
func (m *HashicorpVault_NewSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashicorpVault_NewSecretResponse.Marshal(b, m, deterministic)
}
func (m *HashicorpVault_NewSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashicorpVault_NewSecretResponse.Merge(m, src)
}
func (m *HashicorpVault_NewSecretResponse) XXX_Size() int {
	return xxx_messageInfo_HashicorpVault_NewSecretResponse.Size(m)
}
func (m *HashicorpVault_NewSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashicorpVault_NewSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashicorpVault_NewSecretResponse proto.InternalMessageInfo

func (m *HashicorpVault_NewSecretResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type HashicorpVault_ViewSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashicorpVault_ViewSecretRequest) Reset()         { *m = HashicorpVault_ViewSecretRequest{} }
func (m *HashicorpVault_ViewSecretRequest) String() string { return proto.CompactTextString(m) }
func (*HashicorpVault_ViewSecretRequest) ProtoMessage()    {}
func (*HashicorpVault_ViewSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{2}
}

func (m *HashicorpVault_ViewSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashicorpVault_ViewSecretRequest.Unmarshal(m, b)
}
func (m *HashicorpVault_ViewSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashicorpVault_ViewSecretRequest.Marshal(b, m, deterministic)
}
func (m *HashicorpVault_ViewSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashicorpVault_ViewSecretRequest.Merge(m, src)
}
func (m *HashicorpVault_ViewSecretRequest) XXX_Size() int {
	return xxx_messageInfo_HashicorpVault_ViewSecretRequest.Size(m)
}
func (m *HashicorpVault_ViewSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashicorpVault_ViewSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashicorpVault_ViewSecretRequest proto.InternalMessageInfo

func (m *HashicorpVault_ViewSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type HashicorpVault_ViewSecretResponse struct {
	SecretValue          string   `protobuf:"bytes,1,opt,name=secretValue,proto3" json:"secretValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashicorpVault_ViewSecretResponse) Reset()         { *m = HashicorpVault_ViewSecretResponse{} }
func (m *HashicorpVault_ViewSecretResponse) String() string { return proto.CompactTextString(m) }
func (*HashicorpVault_ViewSecretResponse) ProtoMessage()    {}
func (*HashicorpVault_ViewSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{3}
}

func (m *HashicorpVault_ViewSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashicorpVault_ViewSecretResponse.Unmarshal(m, b)
}
func (m *HashicorpVault_ViewSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashicorpVault_ViewSecretResponse.Marshal(b, m, deterministic)
}
func (m *HashicorpVault_ViewSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashicorpVault_ViewSecretResponse.Merge(m, src)
}
func (m *HashicorpVault_ViewSecretResponse) XXX_Size() int {
	return xxx_messageInfo_HashicorpVault_ViewSecretResponse.Size(m)
}
func (m *HashicorpVault_ViewSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashicorpVault_ViewSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashicorpVault_ViewSecretResponse proto.InternalMessageInfo

func (m *HashicorpVault_ViewSecretResponse) GetSecretValue() string {
	if m != nil {
		return m.SecretValue
	}
	return ""
}

type HashicorpVault_UpdateSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	SecretNewValue       string   `protobuf:"bytes,2,opt,name=secretNewValue,proto3" json:"secretNewValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashicorpVault_UpdateSecretRequest) Reset()         { *m = HashicorpVault_UpdateSecretRequest{} }
func (m *HashicorpVault_UpdateSecretRequest) String() string { return proto.CompactTextString(m) }
func (*HashicorpVault_UpdateSecretRequest) ProtoMessage()    {}
func (*HashicorpVault_UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{4}
}

func (m *HashicorpVault_UpdateSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashicorpVault_UpdateSecretRequest.Unmarshal(m, b)
}
func (m *HashicorpVault_UpdateSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashicorpVault_UpdateSecretRequest.Marshal(b, m, deterministic)
}
func (m *HashicorpVault_UpdateSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashicorpVault_UpdateSecretRequest.Merge(m, src)
}
func (m *HashicorpVault_UpdateSecretRequest) XXX_Size() int {
	return xxx_messageInfo_HashicorpVault_UpdateSecretRequest.Size(m)
}
func (m *HashicorpVault_UpdateSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashicorpVault_UpdateSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashicorpVault_UpdateSecretRequest proto.InternalMessageInfo

func (m *HashicorpVault_UpdateSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *HashicorpVault_UpdateSecretRequest) GetSecretNewValue() string {
	if m != nil {
		return m.SecretNewValue
	}
	return ""
}

type HashicorpVault_UpdateSecretResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SecretOldValue       string   `protobuf:"bytes,2,opt,name=secretOldValue,proto3" json:"secretOldValue,omitempty"`
	SecretNewValue       string   `protobuf:"bytes,3,opt,name=secretNewValue,proto3" json:"secretNewValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashicorpVault_UpdateSecretResponse) Reset()         { *m = HashicorpVault_UpdateSecretResponse{} }
func (m *HashicorpVault_UpdateSecretResponse) String() string { return proto.CompactTextString(m) }
func (*HashicorpVault_UpdateSecretResponse) ProtoMessage()    {}
func (*HashicorpVault_UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{5}
}

func (m *HashicorpVault_UpdateSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashicorpVault_UpdateSecretResponse.Unmarshal(m, b)
}
func (m *HashicorpVault_UpdateSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashicorpVault_UpdateSecretResponse.Marshal(b, m, deterministic)
}
func (m *HashicorpVault_UpdateSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashicorpVault_UpdateSecretResponse.Merge(m, src)
}
func (m *HashicorpVault_UpdateSecretResponse) XXX_Size() int {
	return xxx_messageInfo_HashicorpVault_UpdateSecretResponse.Size(m)
}
func (m *HashicorpVault_UpdateSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashicorpVault_UpdateSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashicorpVault_UpdateSecretResponse proto.InternalMessageInfo

func (m *HashicorpVault_UpdateSecretResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *HashicorpVault_UpdateSecretResponse) GetSecretOldValue() string {
	if m != nil {
		return m.SecretOldValue
	}
	return ""
}

func (m *HashicorpVault_UpdateSecretResponse) GetSecretNewValue() string {
	if m != nil {
		return m.SecretNewValue
	}
	return ""
}

type HashicorpVault_DeleteSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashicorpVault_DeleteSecretRequest) Reset()         { *m = HashicorpVault_DeleteSecretRequest{} }
func (m *HashicorpVault_DeleteSecretRequest) String() string { return proto.CompactTextString(m) }
func (*HashicorpVault_DeleteSecretRequest) ProtoMessage()    {}
func (*HashicorpVault_DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{6}
}

func (m *HashicorpVault_DeleteSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashicorpVault_DeleteSecretRequest.Unmarshal(m, b)
}
func (m *HashicorpVault_DeleteSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashicorpVault_DeleteSecretRequest.Marshal(b, m, deterministic)
}
func (m *HashicorpVault_DeleteSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashicorpVault_DeleteSecretRequest.Merge(m, src)
}
func (m *HashicorpVault_DeleteSecretRequest) XXX_Size() int {
	return xxx_messageInfo_HashicorpVault_DeleteSecretRequest.Size(m)
}
func (m *HashicorpVault_DeleteSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashicorpVault_DeleteSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashicorpVault_DeleteSecretRequest proto.InternalMessageInfo

func (m *HashicorpVault_DeleteSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type HashicorpVault_DeleteSecretResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashicorpVault_DeleteSecretResponse) Reset()         { *m = HashicorpVault_DeleteSecretResponse{} }
func (m *HashicorpVault_DeleteSecretResponse) String() string { return proto.CompactTextString(m) }
func (*HashicorpVault_DeleteSecretResponse) ProtoMessage()    {}
func (*HashicorpVault_DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{7}
}

func (m *HashicorpVault_DeleteSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashicorpVault_DeleteSecretResponse.Unmarshal(m, b)
}
func (m *HashicorpVault_DeleteSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashicorpVault_DeleteSecretResponse.Marshal(b, m, deterministic)
}
func (m *HashicorpVault_DeleteSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashicorpVault_DeleteSecretResponse.Merge(m, src)
}
func (m *HashicorpVault_DeleteSecretResponse) XXX_Size() int {
	return xxx_messageInfo_HashicorpVault_DeleteSecretResponse.Size(m)
}
func (m *HashicorpVault_DeleteSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashicorpVault_DeleteSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashicorpVault_DeleteSecretResponse proto.InternalMessageInfo

func (m *HashicorpVault_DeleteSecretResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AWSSSM_NewSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	SecretValut          string   `protobuf:"bytes,2,opt,name=secretValut,proto3" json:"secretValut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWSSSM_NewSecretRequest) Reset()         { *m = AWSSSM_NewSecretRequest{} }
func (m *AWSSSM_NewSecretRequest) String() string { return proto.CompactTextString(m) }
func (*AWSSSM_NewSecretRequest) ProtoMessage()    {}
func (*AWSSSM_NewSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{8}
}

func (m *AWSSSM_NewSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSSSM_NewSecretRequest.Unmarshal(m, b)
}
func (m *AWSSSM_NewSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSSSM_NewSecretRequest.Marshal(b, m, deterministic)
}
func (m *AWSSSM_NewSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSSSM_NewSecretRequest.Merge(m, src)
}
func (m *AWSSSM_NewSecretRequest) XXX_Size() int {
	return xxx_messageInfo_AWSSSM_NewSecretRequest.Size(m)
}
func (m *AWSSSM_NewSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSSSM_NewSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AWSSSM_NewSecretRequest proto.InternalMessageInfo

func (m *AWSSSM_NewSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *AWSSSM_NewSecretRequest) GetSecretValut() string {
	if m != nil {
		return m.SecretValut
	}
	return ""
}

type AWSSSM_NewSecretResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWSSSM_NewSecretResponse) Reset()         { *m = AWSSSM_NewSecretResponse{} }
func (m *AWSSSM_NewSecretResponse) String() string { return proto.CompactTextString(m) }
func (*AWSSSM_NewSecretResponse) ProtoMessage()    {}
func (*AWSSSM_NewSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{9}
}

func (m *AWSSSM_NewSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSSSM_NewSecretResponse.Unmarshal(m, b)
}
func (m *AWSSSM_NewSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSSSM_NewSecretResponse.Marshal(b, m, deterministic)
}
func (m *AWSSSM_NewSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSSSM_NewSecretResponse.Merge(m, src)
}
func (m *AWSSSM_NewSecretResponse) XXX_Size() int {
	return xxx_messageInfo_AWSSSM_NewSecretResponse.Size(m)
}
func (m *AWSSSM_NewSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSSSM_NewSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AWSSSM_NewSecretResponse proto.InternalMessageInfo

func (m *AWSSSM_NewSecretResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AWSSSM_ViewSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWSSSM_ViewSecretRequest) Reset()         { *m = AWSSSM_ViewSecretRequest{} }
func (m *AWSSSM_ViewSecretRequest) String() string { return proto.CompactTextString(m) }
func (*AWSSSM_ViewSecretRequest) ProtoMessage()    {}
func (*AWSSSM_ViewSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{10}
}

func (m *AWSSSM_ViewSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSSSM_ViewSecretRequest.Unmarshal(m, b)
}
func (m *AWSSSM_ViewSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSSSM_ViewSecretRequest.Marshal(b, m, deterministic)
}
func (m *AWSSSM_ViewSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSSSM_ViewSecretRequest.Merge(m, src)
}
func (m *AWSSSM_ViewSecretRequest) XXX_Size() int {
	return xxx_messageInfo_AWSSSM_ViewSecretRequest.Size(m)
}
func (m *AWSSSM_ViewSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSSSM_ViewSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AWSSSM_ViewSecretRequest proto.InternalMessageInfo

func (m *AWSSSM_ViewSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type AWSSSM_ViewSecretResponse struct {
	SecretValue          string   `protobuf:"bytes,1,opt,name=secretValue,proto3" json:"secretValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWSSSM_ViewSecretResponse) Reset()         { *m = AWSSSM_ViewSecretResponse{} }
func (m *AWSSSM_ViewSecretResponse) String() string { return proto.CompactTextString(m) }
func (*AWSSSM_ViewSecretResponse) ProtoMessage()    {}
func (*AWSSSM_ViewSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{11}
}

func (m *AWSSSM_ViewSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSSSM_ViewSecretResponse.Unmarshal(m, b)
}
func (m *AWSSSM_ViewSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSSSM_ViewSecretResponse.Marshal(b, m, deterministic)
}
func (m *AWSSSM_ViewSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSSSM_ViewSecretResponse.Merge(m, src)
}
func (m *AWSSSM_ViewSecretResponse) XXX_Size() int {
	return xxx_messageInfo_AWSSSM_ViewSecretResponse.Size(m)
}
func (m *AWSSSM_ViewSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSSSM_ViewSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AWSSSM_ViewSecretResponse proto.InternalMessageInfo

func (m *AWSSSM_ViewSecretResponse) GetSecretValue() string {
	if m != nil {
		return m.SecretValue
	}
	return ""
}

type AWSSSM_UpdateSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	SecretNewValue       string   `protobuf:"bytes,2,opt,name=secretNewValue,proto3" json:"secretNewValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWSSSM_UpdateSecretRequest) Reset()         { *m = AWSSSM_UpdateSecretRequest{} }
func (m *AWSSSM_UpdateSecretRequest) String() string { return proto.CompactTextString(m) }
func (*AWSSSM_UpdateSecretRequest) ProtoMessage()    {}
func (*AWSSSM_UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{12}
}

func (m *AWSSSM_UpdateSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSSSM_UpdateSecretRequest.Unmarshal(m, b)
}
func (m *AWSSSM_UpdateSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSSSM_UpdateSecretRequest.Marshal(b, m, deterministic)
}
func (m *AWSSSM_UpdateSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSSSM_UpdateSecretRequest.Merge(m, src)
}
func (m *AWSSSM_UpdateSecretRequest) XXX_Size() int {
	return xxx_messageInfo_AWSSSM_UpdateSecretRequest.Size(m)
}
func (m *AWSSSM_UpdateSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSSSM_UpdateSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AWSSSM_UpdateSecretRequest proto.InternalMessageInfo

func (m *AWSSSM_UpdateSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *AWSSSM_UpdateSecretRequest) GetSecretNewValue() string {
	if m != nil {
		return m.SecretNewValue
	}
	return ""
}

type AWSSSM_UpdateSecretResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SecretOldValue       string   `protobuf:"bytes,2,opt,name=secretOldValue,proto3" json:"secretOldValue,omitempty"`
	SecretNewValue       string   `protobuf:"bytes,3,opt,name=secretNewValue,proto3" json:"secretNewValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWSSSM_UpdateSecretResponse) Reset()         { *m = AWSSSM_UpdateSecretResponse{} }
func (m *AWSSSM_UpdateSecretResponse) String() string { return proto.CompactTextString(m) }
func (*AWSSSM_UpdateSecretResponse) ProtoMessage()    {}
func (*AWSSSM_UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{13}
}

func (m *AWSSSM_UpdateSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSSSM_UpdateSecretResponse.Unmarshal(m, b)
}
func (m *AWSSSM_UpdateSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSSSM_UpdateSecretResponse.Marshal(b, m, deterministic)
}
func (m *AWSSSM_UpdateSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSSSM_UpdateSecretResponse.Merge(m, src)
}
func (m *AWSSSM_UpdateSecretResponse) XXX_Size() int {
	return xxx_messageInfo_AWSSSM_UpdateSecretResponse.Size(m)
}
func (m *AWSSSM_UpdateSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSSSM_UpdateSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AWSSSM_UpdateSecretResponse proto.InternalMessageInfo

func (m *AWSSSM_UpdateSecretResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AWSSSM_UpdateSecretResponse) GetSecretOldValue() string {
	if m != nil {
		return m.SecretOldValue
	}
	return ""
}

func (m *AWSSSM_UpdateSecretResponse) GetSecretNewValue() string {
	if m != nil {
		return m.SecretNewValue
	}
	return ""
}

type AWSSSM_DeleteSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWSSSM_DeleteSecretRequest) Reset()         { *m = AWSSSM_DeleteSecretRequest{} }
func (m *AWSSSM_DeleteSecretRequest) String() string { return proto.CompactTextString(m) }
func (*AWSSSM_DeleteSecretRequest) ProtoMessage()    {}
func (*AWSSSM_DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{14}
}

func (m *AWSSSM_DeleteSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSSSM_DeleteSecretRequest.Unmarshal(m, b)
}
func (m *AWSSSM_DeleteSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSSSM_DeleteSecretRequest.Marshal(b, m, deterministic)
}
func (m *AWSSSM_DeleteSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSSSM_DeleteSecretRequest.Merge(m, src)
}
func (m *AWSSSM_DeleteSecretRequest) XXX_Size() int {
	return xxx_messageInfo_AWSSSM_DeleteSecretRequest.Size(m)
}
func (m *AWSSSM_DeleteSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSSSM_DeleteSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AWSSSM_DeleteSecretRequest proto.InternalMessageInfo

func (m *AWSSSM_DeleteSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type AWSSSM_DeleteSecretResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AWSSSM_DeleteSecretResponse) Reset()         { *m = AWSSSM_DeleteSecretResponse{} }
func (m *AWSSSM_DeleteSecretResponse) String() string { return proto.CompactTextString(m) }
func (*AWSSSM_DeleteSecretResponse) ProtoMessage()    {}
func (*AWSSSM_DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{15}
}

func (m *AWSSSM_DeleteSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AWSSSM_DeleteSecretResponse.Unmarshal(m, b)
}
func (m *AWSSSM_DeleteSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AWSSSM_DeleteSecretResponse.Marshal(b, m, deterministic)
}
func (m *AWSSSM_DeleteSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AWSSSM_DeleteSecretResponse.Merge(m, src)
}
func (m *AWSSSM_DeleteSecretResponse) XXX_Size() int {
	return xxx_messageInfo_AWSSSM_DeleteSecretResponse.Size(m)
}
func (m *AWSSSM_DeleteSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AWSSSM_DeleteSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AWSSSM_DeleteSecretResponse proto.InternalMessageInfo

func (m *AWSSSM_DeleteSecretResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*HashicorpVault_NewSecretRequest)(nil), "environmentalist.HashicorpVault_NewSecretRequest")
	proto.RegisterType((*HashicorpVault_NewSecretResponse)(nil), "environmentalist.HashicorpVault_NewSecretResponse")
	proto.RegisterType((*HashicorpVault_ViewSecretRequest)(nil), "environmentalist.HashicorpVault_ViewSecretRequest")
	proto.RegisterType((*HashicorpVault_ViewSecretResponse)(nil), "environmentalist.HashicorpVault_ViewSecretResponse")
	proto.RegisterType((*HashicorpVault_UpdateSecretRequest)(nil), "environmentalist.HashicorpVault_UpdateSecretRequest")
	proto.RegisterType((*HashicorpVault_UpdateSecretResponse)(nil), "environmentalist.HashicorpVault_UpdateSecretResponse")
	proto.RegisterType((*HashicorpVault_DeleteSecretRequest)(nil), "environmentalist.HashicorpVault_DeleteSecretRequest")
	proto.RegisterType((*HashicorpVault_DeleteSecretResponse)(nil), "environmentalist.HashicorpVault_DeleteSecretResponse")
	proto.RegisterType((*AWSSSM_NewSecretRequest)(nil), "environmentalist.AWSSSM_NewSecretRequest")
	proto.RegisterType((*AWSSSM_NewSecretResponse)(nil), "environmentalist.AWSSSM_NewSecretResponse")
	proto.RegisterType((*AWSSSM_ViewSecretRequest)(nil), "environmentalist.AWSSSM_ViewSecretRequest")
	proto.RegisterType((*AWSSSM_ViewSecretResponse)(nil), "environmentalist.AWSSSM_ViewSecretResponse")
	proto.RegisterType((*AWSSSM_UpdateSecretRequest)(nil), "environmentalist.AWSSSM_UpdateSecretRequest")
	proto.RegisterType((*AWSSSM_UpdateSecretResponse)(nil), "environmentalist.AWSSSM_UpdateSecretResponse")
	proto.RegisterType((*AWSSSM_DeleteSecretRequest)(nil), "environmentalist.AWSSSM_DeleteSecretRequest")
	proto.RegisterType((*AWSSSM_DeleteSecretResponse)(nil), "environmentalist.AWSSSM_DeleteSecretResponse")
}

func init() { proto.RegisterFile("environmentalist.proto", fileDescriptor_2b790fada11e405d) }

var fileDescriptor_2b790fada11e405d = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xde, 0xb8, 0xe2, 0xcf, 0x11, 0x75, 0x19, 0xd4, 0x8d, 0x11, 0xb4, 0x8e, 0x20, 0xba, 0xba,
	0x0b, 0x66, 0x57, 0x04, 0xa9, 0x88, 0xa5, 0x82, 0x37, 0x46, 0x68, 0xb0, 0x82, 0x5e, 0x48, 0x9a,
	0x1e, 0x30, 0x92, 0x26, 0x31, 0x33, 0x69, 0xef, 0x05, 0xf1, 0xc2, 0x0b, 0x5f, 0xc9, 0x87, 0xf0,
	0x81, 0xa4, 0x99, 0x26, 0xe6, 0x67, 0xd2, 0x64, 0x0a, 0xdd, 0xcb, 0x39, 0x9d, 0xef, 0xe7, 0x9c,
	0xf3, 0x75, 0x08, 0xdc, 0xc0, 0x60, 0xee, 0xc5, 0x61, 0x30, 0xc3, 0x80, 0x3b, 0xbe, 0xc7, 0xf8,
	0x51, 0x14, 0x87, 0x3c, 0x24, 0x7b, 0xd5, 0x3a, 0x75, 0xe1, 0xce, 0x1b, 0x87, 0x7d, 0xf1, 0xdc,
	0x30, 0x8e, 0xc6, 0x4e, 0xe2, 0xf3, 0xcf, 0x16, 0x2e, 0x6c, 0x74, 0x63, 0xe4, 0x23, 0xfc, 0x96,
	0x20, 0xe3, 0xe4, 0x36, 0x00, 0x4b, 0x0b, 0x96, 0x33, 0x43, 0x5d, 0xeb, 0x69, 0x0f, 0x2e, 0x8e,
	0x0a, 0x15, 0xd2, 0x83, 0x4b, 0xe2, 0x34, 0x76, 0xfc, 0x84, 0xeb, 0x67, 0xd2, 0x0b, 0xc5, 0x12,
	0xed, 0x43, 0xaf, 0x59, 0x84, 0x45, 0x61, 0xc0, 0x90, 0xe8, 0x70, 0x9e, 0x25, 0xae, 0x8b, 0x8c,
	0xa5, 0x12, 0x17, 0x46, 0xd9, 0x91, 0x0e, 0x6a, 0xe8, 0xb1, 0xa7, 0xe8, 0x91, 0xbe, 0x86, 0xbb,
	0x6b, 0x38, 0x56, 0x16, 0x4a, 0x8d, 0x64, 0x2c, 0xc5, 0x12, 0xf5, 0x81, 0x56, 0x68, 0xde, 0x47,
	0x53, 0x87, 0xa3, 0xda, 0xc0, 0xee, 0xc3, 0x95, 0xd5, 0x09, 0x17, 0x42, 0x4a, 0xcc, 0xac, 0x52,
	0xa5, 0xbf, 0x35, 0xb8, 0xb7, 0x56, 0xae, 0x6d, 0x74, 0xff, 0x95, 0xde, 0xf9, 0x53, 0x89, 0x52,
	0x56, 0x95, 0x38, 0xda, 0x95, 0x3a, 0x1a, 0xd6, 0xfa, 0x1f, 0xa2, 0x8f, 0x8a, 0xfd, 0xd3, 0x97,
	0xb5, 0xb6, 0xca, 0x2c, 0xad, 0x89, 0xf8, 0x04, 0xfb, 0xaf, 0x3e, 0xd8, 0xb6, 0xfd, 0x76, 0x1b,
	0x61, 0x3d, 0x01, 0xbd, 0x4e, 0xde, 0x6a, 0xe9, 0x79, 0x8e, 0x52, 0x0f, 0xe7, 0x0b, 0xb8, 0x29,
	0xc1, 0x76, 0x0e, 0xe5, 0x14, 0x8c, 0x15, 0x7c, 0x9b, 0x61, 0xfc, 0xa9, 0xc1, 0x2d, 0xa9, 0xcc,
	0xa9, 0x87, 0xb0, 0x9f, 0xf7, 0xbb, 0x49, 0xf8, 0x9e, 0xe5, 0x6d, 0xa8, 0x85, 0xce, 0xfc, 0x73,
	0x16, 0xae, 0x97, 0x63, 0x6b, 0x63, 0x3c, 0xf7, 0x5c, 0x24, 0x3f, 0x34, 0xd0, 0x97, 0x9b, 0xab,
	0xfe, 0xba, 0x24, 0x26, 0xe6, 0x51, 0xed, 0x2d, 0x6e, 0x7b, 0xcd, 0x8c, 0x63, 0x25, 0x8c, 0x70,
	0x4e, 0x77, 0xc8, 0x77, 0x0d, 0xf6, 0xad, 0x06, 0x1b, 0x4f, 0x5a, 0x29, 0xab, 0x7f, 0x25, 0xc3,
	0x54, 0x81, 0xe4, 0x26, 0x7e, 0x69, 0x60, 0x88, 0x80, 0x48, 0x7d, 0x9c, 0xb4, 0x92, 0x4a, 0x42,
	0x6c, 0x3c, 0x55, 0x44, 0x95, 0xdc, 0x88, 0x3d, 0x6f, 0xe8, 0x46, 0x12, 0xb1, 0x0e, 0x6e, 0x64,
	0xd1, 0xa2, 0x3b, 0xe6, 0xdf, 0x5d, 0xb8, 0x2c, 0xc2, 0x97, 0x45, 0x67, 0x06, 0x7b, 0xcb, 0x55,
	0x66, 0xc5, 0xd4, 0xd4, 0x41, 0x9d, 0xbe, 0xe9, 0x69, 0x31, 0x1e, 0x75, 0xba, 0x9b, 0x8f, 0xe3,
	0x2b, 0x5c, 0xb5, 0x2a, 0x6a, 0x0f, 0x1b, 0x19, 0x6a, 0x81, 0x38, 0xe8, 0x72, 0x35, 0xd7, 0x62,
	0x40, 0xc4, 0x52, 0x4a, 0x72, 0x8f, 0x1b, 0x39, 0x64, 0x7b, 0x3f, 0xec, 0x78, 0xbb, 0x28, 0x2a,
	0x66, 0xdf, 0x51, 0x54, 0xb6, 0xde, 0xc3, 0x8e, 0xb7, 0x33, 0xd1, 0xc1, 0xb5, 0x8f, 0xa4, 0x8a,
	0x88, 0x26, 0x93, 0x73, 0xe9, 0x27, 0xd7, 0xf1, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x76,
	0xea, 0xb5, 0x8c, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HashicorpVaultServiceClient is the client API for HashicorpVaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HashicorpVaultServiceClient interface {
	ViewHashicorpVaultSecret(ctx context.Context, in *HashicorpVault_ViewSecretRequest, opts ...grpc.CallOption) (*HashicorpVault_ViewSecretResponse, error)
	NewHashicorpVaultSecret(ctx context.Context, in *HashicorpVault_NewSecretRequest, opts ...grpc.CallOption) (*HashicorpVault_NewSecretResponse, error)
	UpdateHashicorpVaultSecret(ctx context.Context, in *HashicorpVault_UpdateSecretRequest, opts ...grpc.CallOption) (*HashicorpVault_UpdateSecretResponse, error)
	DeleteHashicorpVaultSecret(ctx context.Context, in *HashicorpVault_DeleteSecretRequest, opts ...grpc.CallOption) (*HashicorpVault_DeleteSecretResponse, error)
}

type hashicorpVaultServiceClient struct {
	cc *grpc.ClientConn
}

func NewHashicorpVaultServiceClient(cc *grpc.ClientConn) HashicorpVaultServiceClient {
	return &hashicorpVaultServiceClient{cc}
}

func (c *hashicorpVaultServiceClient) ViewHashicorpVaultSecret(ctx context.Context, in *HashicorpVault_ViewSecretRequest, opts ...grpc.CallOption) (*HashicorpVault_ViewSecretResponse, error) {
	out := new(HashicorpVault_ViewSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.HashicorpVaultService/ViewHashicorpVaultSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashicorpVaultServiceClient) NewHashicorpVaultSecret(ctx context.Context, in *HashicorpVault_NewSecretRequest, opts ...grpc.CallOption) (*HashicorpVault_NewSecretResponse, error) {
	out := new(HashicorpVault_NewSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.HashicorpVaultService/NewHashicorpVaultSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashicorpVaultServiceClient) UpdateHashicorpVaultSecret(ctx context.Context, in *HashicorpVault_UpdateSecretRequest, opts ...grpc.CallOption) (*HashicorpVault_UpdateSecretResponse, error) {
	out := new(HashicorpVault_UpdateSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.HashicorpVaultService/UpdateHashicorpVaultSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashicorpVaultServiceClient) DeleteHashicorpVaultSecret(ctx context.Context, in *HashicorpVault_DeleteSecretRequest, opts ...grpc.CallOption) (*HashicorpVault_DeleteSecretResponse, error) {
	out := new(HashicorpVault_DeleteSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.HashicorpVaultService/DeleteHashicorpVaultSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashicorpVaultServiceServer is the server API for HashicorpVaultService service.
type HashicorpVaultServiceServer interface {
	ViewHashicorpVaultSecret(context.Context, *HashicorpVault_ViewSecretRequest) (*HashicorpVault_ViewSecretResponse, error)
	NewHashicorpVaultSecret(context.Context, *HashicorpVault_NewSecretRequest) (*HashicorpVault_NewSecretResponse, error)
	UpdateHashicorpVaultSecret(context.Context, *HashicorpVault_UpdateSecretRequest) (*HashicorpVault_UpdateSecretResponse, error)
	DeleteHashicorpVaultSecret(context.Context, *HashicorpVault_DeleteSecretRequest) (*HashicorpVault_DeleteSecretResponse, error)
}

// UnimplementedHashicorpVaultServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHashicorpVaultServiceServer struct {
}

func (*UnimplementedHashicorpVaultServiceServer) ViewHashicorpVaultSecret(ctx context.Context, req *HashicorpVault_ViewSecretRequest) (*HashicorpVault_ViewSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewHashicorpVaultSecret not implemented")
}
func (*UnimplementedHashicorpVaultServiceServer) NewHashicorpVaultSecret(ctx context.Context, req *HashicorpVault_NewSecretRequest) (*HashicorpVault_NewSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewHashicorpVaultSecret not implemented")
}
func (*UnimplementedHashicorpVaultServiceServer) UpdateHashicorpVaultSecret(ctx context.Context, req *HashicorpVault_UpdateSecretRequest) (*HashicorpVault_UpdateSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHashicorpVaultSecret not implemented")
}
func (*UnimplementedHashicorpVaultServiceServer) DeleteHashicorpVaultSecret(ctx context.Context, req *HashicorpVault_DeleteSecretRequest) (*HashicorpVault_DeleteSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHashicorpVaultSecret not implemented")
}

func RegisterHashicorpVaultServiceServer(s *grpc.Server, srv HashicorpVaultServiceServer) {
	s.RegisterService(&_HashicorpVaultService_serviceDesc, srv)
}

func _HashicorpVaultService_ViewHashicorpVaultSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashicorpVault_ViewSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashicorpVaultServiceServer).ViewHashicorpVaultSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.HashicorpVaultService/ViewHashicorpVaultSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashicorpVaultServiceServer).ViewHashicorpVaultSecret(ctx, req.(*HashicorpVault_ViewSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashicorpVaultService_NewHashicorpVaultSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashicorpVault_NewSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashicorpVaultServiceServer).NewHashicorpVaultSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.HashicorpVaultService/NewHashicorpVaultSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashicorpVaultServiceServer).NewHashicorpVaultSecret(ctx, req.(*HashicorpVault_NewSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashicorpVaultService_UpdateHashicorpVaultSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashicorpVault_UpdateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashicorpVaultServiceServer).UpdateHashicorpVaultSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.HashicorpVaultService/UpdateHashicorpVaultSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashicorpVaultServiceServer).UpdateHashicorpVaultSecret(ctx, req.(*HashicorpVault_UpdateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashicorpVaultService_DeleteHashicorpVaultSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashicorpVault_DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashicorpVaultServiceServer).DeleteHashicorpVaultSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.HashicorpVaultService/DeleteHashicorpVaultSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashicorpVaultServiceServer).DeleteHashicorpVaultSecret(ctx, req.(*HashicorpVault_DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HashicorpVaultService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "environmentalist.HashicorpVaultService",
	HandlerType: (*HashicorpVaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ViewHashicorpVaultSecret",
			Handler:    _HashicorpVaultService_ViewHashicorpVaultSecret_Handler,
		},
		{
			MethodName: "NewHashicorpVaultSecret",
			Handler:    _HashicorpVaultService_NewHashicorpVaultSecret_Handler,
		},
		{
			MethodName: "UpdateHashicorpVaultSecret",
			Handler:    _HashicorpVaultService_UpdateHashicorpVaultSecret_Handler,
		},
		{
			MethodName: "DeleteHashicorpVaultSecret",
			Handler:    _HashicorpVaultService_DeleteHashicorpVaultSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "environmentalist.proto",
}

// AWSSSMServiceClient is the client API for AWSSSMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AWSSSMServiceClient interface {
	ViewAWSSSMSecret(ctx context.Context, in *AWSSSM_ViewSecretRequest, opts ...grpc.CallOption) (*AWSSSM_ViewSecretResponse, error)
	NewAWSSSMSecret(ctx context.Context, in *AWSSSM_NewSecretRequest, opts ...grpc.CallOption) (*AWSSSM_NewSecretResponse, error)
	UpdateAWSSSMSecret(ctx context.Context, in *AWSSSM_UpdateSecretRequest, opts ...grpc.CallOption) (*AWSSSM_UpdateSecretResponse, error)
	DeleteAWSSSMSecret(ctx context.Context, in *AWSSSM_DeleteSecretRequest, opts ...grpc.CallOption) (*AWSSSM_DeleteSecretResponse, error)
}

type aWSSSMServiceClient struct {
	cc *grpc.ClientConn
}

func NewAWSSSMServiceClient(cc *grpc.ClientConn) AWSSSMServiceClient {
	return &aWSSSMServiceClient{cc}
}

func (c *aWSSSMServiceClient) ViewAWSSSMSecret(ctx context.Context, in *AWSSSM_ViewSecretRequest, opts ...grpc.CallOption) (*AWSSSM_ViewSecretResponse, error) {
	out := new(AWSSSM_ViewSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.AWSSSMService/ViewAWSSSMSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSSSMServiceClient) NewAWSSSMSecret(ctx context.Context, in *AWSSSM_NewSecretRequest, opts ...grpc.CallOption) (*AWSSSM_NewSecretResponse, error) {
	out := new(AWSSSM_NewSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.AWSSSMService/NewAWSSSMSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSSSMServiceClient) UpdateAWSSSMSecret(ctx context.Context, in *AWSSSM_UpdateSecretRequest, opts ...grpc.CallOption) (*AWSSSM_UpdateSecretResponse, error) {
	out := new(AWSSSM_UpdateSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.AWSSSMService/UpdateAWSSSMSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aWSSSMServiceClient) DeleteAWSSSMSecret(ctx context.Context, in *AWSSSM_DeleteSecretRequest, opts ...grpc.CallOption) (*AWSSSM_DeleteSecretResponse, error) {
	out := new(AWSSSM_DeleteSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.AWSSSMService/DeleteAWSSSMSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AWSSSMServiceServer is the server API for AWSSSMService service.
type AWSSSMServiceServer interface {
	ViewAWSSSMSecret(context.Context, *AWSSSM_ViewSecretRequest) (*AWSSSM_ViewSecretResponse, error)
	NewAWSSSMSecret(context.Context, *AWSSSM_NewSecretRequest) (*AWSSSM_NewSecretResponse, error)
	UpdateAWSSSMSecret(context.Context, *AWSSSM_UpdateSecretRequest) (*AWSSSM_UpdateSecretResponse, error)
	DeleteAWSSSMSecret(context.Context, *AWSSSM_DeleteSecretRequest) (*AWSSSM_DeleteSecretResponse, error)
}

// UnimplementedAWSSSMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAWSSSMServiceServer struct {
}

func (*UnimplementedAWSSSMServiceServer) ViewAWSSSMSecret(ctx context.Context, req *AWSSSM_ViewSecretRequest) (*AWSSSM_ViewSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewAWSSSMSecret not implemented")
}
func (*UnimplementedAWSSSMServiceServer) NewAWSSSMSecret(ctx context.Context, req *AWSSSM_NewSecretRequest) (*AWSSSM_NewSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewAWSSSMSecret not implemented")
}
func (*UnimplementedAWSSSMServiceServer) UpdateAWSSSMSecret(ctx context.Context, req *AWSSSM_UpdateSecretRequest) (*AWSSSM_UpdateSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAWSSSMSecret not implemented")
}
func (*UnimplementedAWSSSMServiceServer) DeleteAWSSSMSecret(ctx context.Context, req *AWSSSM_DeleteSecretRequest) (*AWSSSM_DeleteSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAWSSSMSecret not implemented")
}

func RegisterAWSSSMServiceServer(s *grpc.Server, srv AWSSSMServiceServer) {
	s.RegisterService(&_AWSSSMService_serviceDesc, srv)
}

func _AWSSSMService_ViewAWSSSMSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AWSSSM_ViewSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSSSMServiceServer).ViewAWSSSMSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.AWSSSMService/ViewAWSSSMSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSSSMServiceServer).ViewAWSSSMSecret(ctx, req.(*AWSSSM_ViewSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSSSMService_NewAWSSSMSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AWSSSM_NewSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSSSMServiceServer).NewAWSSSMSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.AWSSSMService/NewAWSSSMSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSSSMServiceServer).NewAWSSSMSecret(ctx, req.(*AWSSSM_NewSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSSSMService_UpdateAWSSSMSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AWSSSM_UpdateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSSSMServiceServer).UpdateAWSSSMSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.AWSSSMService/UpdateAWSSSMSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSSSMServiceServer).UpdateAWSSSMSecret(ctx, req.(*AWSSSM_UpdateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AWSSSMService_DeleteAWSSSMSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AWSSSM_DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AWSSSMServiceServer).DeleteAWSSSMSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.AWSSSMService/DeleteAWSSSMSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AWSSSMServiceServer).DeleteAWSSSMSecret(ctx, req.(*AWSSSM_DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AWSSSMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "environmentalist.AWSSSMService",
	HandlerType: (*AWSSSMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ViewAWSSSMSecret",
			Handler:    _AWSSSMService_ViewAWSSSMSecret_Handler,
		},
		{
			MethodName: "NewAWSSSMSecret",
			Handler:    _AWSSSMService_NewAWSSSMSecret_Handler,
		},
		{
			MethodName: "UpdateAWSSSMSecret",
			Handler:    _AWSSSMService_UpdateAWSSSMSecret_Handler,
		},
		{
			MethodName: "DeleteAWSSSMSecret",
			Handler:    _AWSSSMService_DeleteAWSSSMSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "environmentalist.proto",
}
