// Code generated by protoc-gen-go. DO NOT EDIT.
// source: environmentalist.proto

package environmentalistpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	SecretValut          string   `protobuf:"bytes,2,opt,name=secretValut,proto3" json:"secretValut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSecretRequest) Reset()         { *m = NewSecretRequest{} }
func (m *NewSecretRequest) String() string { return proto.CompactTextString(m) }
func (*NewSecretRequest) ProtoMessage()    {}
func (*NewSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{0}
}

func (m *NewSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSecretRequest.Unmarshal(m, b)
}
func (m *NewSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSecretRequest.Marshal(b, m, deterministic)
}
func (m *NewSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSecretRequest.Merge(m, src)
}
func (m *NewSecretRequest) XXX_Size() int {
	return xxx_messageInfo_NewSecretRequest.Size(m)
}
func (m *NewSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewSecretRequest proto.InternalMessageInfo

func (m *NewSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *NewSecretRequest) GetSecretValut() string {
	if m != nil {
		return m.SecretValut
	}
	return ""
}

type NewSecretResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSecretResponse) Reset()         { *m = NewSecretResponse{} }
func (m *NewSecretResponse) String() string { return proto.CompactTextString(m) }
func (*NewSecretResponse) ProtoMessage()    {}
func (*NewSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{1}
}

func (m *NewSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSecretResponse.Unmarshal(m, b)
}
func (m *NewSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSecretResponse.Marshal(b, m, deterministic)
}
func (m *NewSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSecretResponse.Merge(m, src)
}
func (m *NewSecretResponse) XXX_Size() int {
	return xxx_messageInfo_NewSecretResponse.Size(m)
}
func (m *NewSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewSecretResponse proto.InternalMessageInfo

func (m *NewSecretResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ViewSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewSecretRequest) Reset()         { *m = ViewSecretRequest{} }
func (m *ViewSecretRequest) String() string { return proto.CompactTextString(m) }
func (*ViewSecretRequest) ProtoMessage()    {}
func (*ViewSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{2}
}

func (m *ViewSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewSecretRequest.Unmarshal(m, b)
}
func (m *ViewSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewSecretRequest.Marshal(b, m, deterministic)
}
func (m *ViewSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewSecretRequest.Merge(m, src)
}
func (m *ViewSecretRequest) XXX_Size() int {
	return xxx_messageInfo_ViewSecretRequest.Size(m)
}
func (m *ViewSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ViewSecretRequest proto.InternalMessageInfo

func (m *ViewSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type ViewSecretResponse struct {
	SecretValue          string   `protobuf:"bytes,1,opt,name=secretValue,proto3" json:"secretValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewSecretResponse) Reset()         { *m = ViewSecretResponse{} }
func (m *ViewSecretResponse) String() string { return proto.CompactTextString(m) }
func (*ViewSecretResponse) ProtoMessage()    {}
func (*ViewSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{3}
}

func (m *ViewSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewSecretResponse.Unmarshal(m, b)
}
func (m *ViewSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewSecretResponse.Marshal(b, m, deterministic)
}
func (m *ViewSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewSecretResponse.Merge(m, src)
}
func (m *ViewSecretResponse) XXX_Size() int {
	return xxx_messageInfo_ViewSecretResponse.Size(m)
}
func (m *ViewSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ViewSecretResponse proto.InternalMessageInfo

func (m *ViewSecretResponse) GetSecretValue() string {
	if m != nil {
		return m.SecretValue
	}
	return ""
}

type UpdateSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	SecretNewValue       string   `protobuf:"bytes,2,opt,name=secretNewValue,proto3" json:"secretNewValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSecretRequest) Reset()         { *m = UpdateSecretRequest{} }
func (m *UpdateSecretRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSecretRequest) ProtoMessage()    {}
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{4}
}

func (m *UpdateSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSecretRequest.Unmarshal(m, b)
}
func (m *UpdateSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSecretRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSecretRequest.Merge(m, src)
}
func (m *UpdateSecretRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSecretRequest.Size(m)
}
func (m *UpdateSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSecretRequest proto.InternalMessageInfo

func (m *UpdateSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *UpdateSecretRequest) GetSecretNewValue() string {
	if m != nil {
		return m.SecretNewValue
	}
	return ""
}

type UpdateSecretResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SecretOldValue       string   `protobuf:"bytes,2,opt,name=secretOldValue,proto3" json:"secretOldValue,omitempty"`
	SecretNewValue       string   `protobuf:"bytes,3,opt,name=secretNewValue,proto3" json:"secretNewValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSecretResponse) Reset()         { *m = UpdateSecretResponse{} }
func (m *UpdateSecretResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSecretResponse) ProtoMessage()    {}
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{5}
}

func (m *UpdateSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSecretResponse.Unmarshal(m, b)
}
func (m *UpdateSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSecretResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSecretResponse.Merge(m, src)
}
func (m *UpdateSecretResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSecretResponse.Size(m)
}
func (m *UpdateSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSecretResponse proto.InternalMessageInfo

func (m *UpdateSecretResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateSecretResponse) GetSecretOldValue() string {
	if m != nil {
		return m.SecretOldValue
	}
	return ""
}

func (m *UpdateSecretResponse) GetSecretNewValue() string {
	if m != nil {
		return m.SecretNewValue
	}
	return ""
}

type DeleteSecretRequest struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSecretRequest) Reset()         { *m = DeleteSecretRequest{} }
func (m *DeleteSecretRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSecretRequest) ProtoMessage()    {}
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{6}
}

func (m *DeleteSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSecretRequest.Unmarshal(m, b)
}
func (m *DeleteSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSecretRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSecretRequest.Merge(m, src)
}
func (m *DeleteSecretRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSecretRequest.Size(m)
}
func (m *DeleteSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSecretRequest proto.InternalMessageInfo

func (m *DeleteSecretRequest) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type DeleteSecretResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSecretResponse) Reset()         { *m = DeleteSecretResponse{} }
func (m *DeleteSecretResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSecretResponse) ProtoMessage()    {}
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b790fada11e405d, []int{7}
}

func (m *DeleteSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSecretResponse.Unmarshal(m, b)
}
func (m *DeleteSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSecretResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSecretResponse.Merge(m, src)
}
func (m *DeleteSecretResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSecretResponse.Size(m)
}
func (m *DeleteSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSecretResponse proto.InternalMessageInfo

func (m *DeleteSecretResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*NewSecretRequest)(nil), "environmentalist.NewSecretRequest")
	proto.RegisterType((*NewSecretResponse)(nil), "environmentalist.NewSecretResponse")
	proto.RegisterType((*ViewSecretRequest)(nil), "environmentalist.ViewSecretRequest")
	proto.RegisterType((*ViewSecretResponse)(nil), "environmentalist.ViewSecretResponse")
	proto.RegisterType((*UpdateSecretRequest)(nil), "environmentalist.UpdateSecretRequest")
	proto.RegisterType((*UpdateSecretResponse)(nil), "environmentalist.UpdateSecretResponse")
	proto.RegisterType((*DeleteSecretRequest)(nil), "environmentalist.DeleteSecretRequest")
	proto.RegisterType((*DeleteSecretResponse)(nil), "environmentalist.DeleteSecretResponse")
}

func init() { proto.RegisterFile("environmentalist.proto", fileDescriptor_2b790fada11e405d) }

var fileDescriptor_2b790fada11e405d = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0x2c, 0xa8, 0x1d, 0x3f, 0x68, 0xa7, 0x41, 0x42, 0x0e, 0x52, 0xb6, 0x5a, 0xbc, 0x58,
	0xc4, 0xa2, 0x3f, 0x40, 0x3c, 0x57, 0x48, 0x35, 0xa0, 0x20, 0x92, 0xa6, 0x73, 0x08, 0xa4, 0x49,
	0xcc, 0x6e, 0xda, 0xab, 0x07, 0x7f, 0x78, 0x21, 0x69, 0xda, 0x4d, 0xb2, 0x34, 0xe4, 0xb8, 0x8f,
	0xf7, 0xde, 0xbc, 0xc9, 0x9b, 0xc0, 0x15, 0x05, 0x2b, 0x2f, 0x0e, 0x83, 0x25, 0x05, 0xc2, 0xf1,
	0x3d, 0x2e, 0xc6, 0x51, 0x1c, 0x8a, 0x10, 0xbb, 0x65, 0x9c, 0xbd, 0x43, 0x77, 0x4a, 0xeb, 0x19,
	0xb9, 0x31, 0x09, 0x8b, 0x7e, 0x13, 0xe2, 0x02, 0xaf, 0x01, 0x78, 0x0a, 0x4c, 0x9d, 0x25, 0x19,
	0xda, 0x40, 0xbb, 0xeb, 0x58, 0x12, 0x82, 0x03, 0x38, 0xcb, 0x5e, 0xb6, 0xe3, 0x27, 0xc2, 0x38,
	0x4a, 0x09, 0x32, 0xc4, 0xee, 0xa1, 0x27, 0xb9, 0xf2, 0x28, 0x0c, 0x38, 0xa1, 0x01, 0x27, 0x3c,
	0x71, 0x5d, 0xe2, 0x3c, 0xf5, 0x3c, 0xb5, 0xf2, 0x27, 0x9b, 0x40, 0xcf, 0xf6, 0x1a, 0xa6, 0x60,
	0xcf, 0x80, 0xb2, 0x68, 0x3b, 0xa4, 0x90, 0x2d, 0x97, 0xc9, 0x10, 0xfb, 0x86, 0xfe, 0x47, 0xb4,
	0x70, 0x04, 0x35, 0x5b, 0x7a, 0x04, 0x97, 0xdb, 0x17, 0xad, 0x33, 0xef, 0x6c, 0xef, 0x12, 0xca,
	0xfe, 0x34, 0xd0, 0x8b, 0xfe, 0x75, 0xeb, 0xef, 0xad, 0xdf, 0xfc, 0x85, 0xc2, 0x3a, 0x47, 0x15,
	0x11, 0xda, 0xca, 0x08, 0x4f, 0xd0, 0x7f, 0x25, 0x9f, 0x1a, 0x6e, 0xc8, 0x1e, 0x40, 0x2f, 0xca,
	0xea, 0x82, 0x3f, 0xfe, 0xb7, 0xe1, 0x22, 0x23, 0xcf, 0x28, 0x5e, 0x79, 0x2e, 0xe1, 0x27, 0xc0,
	0xbe, 0x14, 0x1c, 0x8e, 0x2b, 0x77, 0x58, 0xe9, 0xd9, 0xbc, 0x39, 0x4c, 0xca, 0x42, 0xb0, 0x16,
	0xda, 0xd0, 0xd9, 0xdd, 0x14, 0xb2, 0xaa, 0xa8, 0x7c, 0xc6, 0xe6, 0xf0, 0x20, 0x67, 0xe7, 0xfb,
	0x03, 0xe7, 0x72, 0x5f, 0x78, 0x5b, 0x95, 0x29, 0xee, 0xc5, 0x1c, 0xd5, 0xd1, 0xe4, 0x01, 0xf2,
	0x77, 0x55, 0x0d, 0x50, 0xd4, 0xa5, 0x1a, 0xa0, 0xaa, 0x87, 0xb5, 0x5e, 0xf4, 0x2f, 0x2c, 0x53,
	0xa3, 0xf9, 0xfc, 0x38, 0xfd, 0xe5, 0x27, 0x9b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0x20, 0x0e,
	0x5b, 0x0c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecretServiceClient is the client API for SecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecretServiceClient interface {
	ViewSecret(ctx context.Context, in *ViewSecretRequest, opts ...grpc.CallOption) (*ViewSecretResponse, error)
	NewSecret(ctx context.Context, in *NewSecretRequest, opts ...grpc.CallOption) (*NewSecretResponse, error)
	UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error)
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error)
}

type secretServiceClient struct {
	cc *grpc.ClientConn
}

func NewSecretServiceClient(cc *grpc.ClientConn) SecretServiceClient {
	return &secretServiceClient{cc}
}

func (c *secretServiceClient) ViewSecret(ctx context.Context, in *ViewSecretRequest, opts ...grpc.CallOption) (*ViewSecretResponse, error) {
	out := new(ViewSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.SecretService/ViewSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) NewSecret(ctx context.Context, in *NewSecretRequest, opts ...grpc.CallOption) (*NewSecretResponse, error) {
	out := new(NewSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.SecretService/NewSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error) {
	out := new(UpdateSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.SecretService/UpdateSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error) {
	out := new(DeleteSecretResponse)
	err := c.cc.Invoke(ctx, "/environmentalist.SecretService/DeleteSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretServiceServer is the server API for SecretService service.
type SecretServiceServer interface {
	ViewSecret(context.Context, *ViewSecretRequest) (*ViewSecretResponse, error)
	NewSecret(context.Context, *NewSecretRequest) (*NewSecretResponse, error)
	UpdateSecret(context.Context, *UpdateSecretRequest) (*UpdateSecretResponse, error)
	DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error)
}

// UnimplementedSecretServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSecretServiceServer struct {
}

func (*UnimplementedSecretServiceServer) ViewSecret(ctx context.Context, req *ViewSecretRequest) (*ViewSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewSecret not implemented")
}
func (*UnimplementedSecretServiceServer) NewSecret(ctx context.Context, req *NewSecretRequest) (*NewSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewSecret not implemented")
}
func (*UnimplementedSecretServiceServer) UpdateSecret(ctx context.Context, req *UpdateSecretRequest) (*UpdateSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSecret not implemented")
}
func (*UnimplementedSecretServiceServer) DeleteSecret(ctx context.Context, req *DeleteSecretRequest) (*DeleteSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSecret not implemented")
}

func RegisterSecretServiceServer(s *grpc.Server, srv SecretServiceServer) {
	s.RegisterService(&_SecretService_serviceDesc, srv)
}

func _SecretService_ViewSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).ViewSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.SecretService/ViewSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).ViewSecret(ctx, req.(*ViewSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_NewSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).NewSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.SecretService/NewSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).NewSecret(ctx, req.(*NewSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_UpdateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).UpdateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.SecretService/UpdateSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).UpdateSecret(ctx, req.(*UpdateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/environmentalist.SecretService/DeleteSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecretService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "environmentalist.SecretService",
	HandlerType: (*SecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ViewSecret",
			Handler:    _SecretService_ViewSecret_Handler,
		},
		{
			MethodName: "NewSecret",
			Handler:    _SecretService_NewSecret_Handler,
		},
		{
			MethodName: "UpdateSecret",
			Handler:    _SecretService_UpdateSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _SecretService_DeleteSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "environmentalist.proto",
}
